
#数据库配置
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver            # mysql驱动包
        url: jdbc:mysql://localhost:3306/sell?useSSL=false&serverTimezone=GMT%2B8            # 数据库名称
        username: root
        password: root
    jpa:
        show-sql: true
    jackson:
        default-property-inclusion: non_null                 #null值过滤

    dbcp2:
        min-idle: 5                                           # 数据库连接池的最小维持连接数
        initial-size: 5                                       # 初始化连接数
        max-total: 5                                          # 最大连接数
        max-wait-millis: 200                                  # 等待连接获取

server:
  servlet:
    context-path: /sell



#配置日志
#logging:
#    pattern:
#        console: "%d - %msg%n"
#    #path: D:\XSJ\Java\IDEAWorkSpace\sell\log
#    file: D:\XSJ\Java\IDEAWorkSpace\sell\log\sell.log
#    level: debug

#微信数据配置
wechat:
    mpAppid: wxd670bc2d4a5f509b
    mpAppSecret: a22dcb18dae4b1ffebffc9750d1ae17c
    mchId: 1483469312
    mchKey: C5245D70627C1F8E9964D494B0735025
    keyPath:
